#!/bin/bash

{% from 'state2/map.jinja' import salt_file_value with context %}

cat << 'EOF' > /tmp/out
{{ conditional_pillar }}

{{ salt_file_value }}

{% set in_file_value = pillar.get('conditional_pillar', 'not_set') %}
{{ in_file_value }}
EOF
